
import './globals.css'
import { Saira } from 'next/font/google'

import { Header } from './components/header'
import { DefaultProviders } from './components/defaukt-provides'

const saira = Saira({ 
  weight: ['300', '400', '500', '600'],
  subsets: ['latin']
 })

export const metadata = {
  title: 'Depart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <DefaultProviders>
          <Header/>
          {children}
        </DefaultProviders>
      </body>
    </html>
  )
}